language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
# command to install dependencies
install:
  - pip install --upgrade pip wheel
  - pip install -r test_requirements.txt
  - pip install .
# command to run tests
script: 
  - export PYTHONPATH=./tests/:$PYTHONPATH
  - cd tests && py.test . -vv
